kind: pipeline
type: docker
name: default

image:
tasks:
  -
steps:
- name: backend
  image: python:alpine
  commands:
  - cd backend
  - apk add --no-cache gcc musl-dev python3-dev
  - pip install --upgrade pip && pip install -r requirements.txt
  - python3 configure.py
  - coverage run manage.py test
  - coverage report
