# Generated by Django 4.2.2 on 2023-07-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedIdentifierSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
